version: 2

project_name: z13ctl

before:
  hooks:
    - go mod tidy
    - go run ./tools/gendocs docs

builds:
  - id: z13ctl
    binary: z13ctl
    ldflags:
      - -s -w -X z13ctl/cmd.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: z13ctl
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - docs/*.md

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto
