version: 2

project_name: z13ctl

before:
  hooks:
    - go mod tidy

builds:
  - id: z13ctl
    binary: z13ctl
    ldflags:
      - -s -w -X github.com/dahui/z13ctl/cmd.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: z13ctl
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - contrib/systemd/**/*

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto
