package cmd

// setup.go — "setup" subcommand: install udev rules for non-root device access.

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/spf13/cobra"
)

const rulesPath = "/etc/udev/rules.d/99-voltaire.rules"
const servicePath = "/etc/systemd/system/voltaire-perms.service"

// The pre-rename artifact locations. setup removes them — the rules file only
// after verifying it is ours (see cleanupOldArtifacts), the unit with an
// explicit disable first: z13ctl-perms.service is Type=oneshot with
// RemainAfterExit=yes, so without the disable it stays active holding stale
// grants until the next reboot.
const oldRulesPath = "/etc/udev/rules.d/99-z13ctl.rules"
const oldServicePath = "/etc/systemd/system/z13ctl-perms.service"
const oldServiceName = "z13ctl-perms.service"

var (
	setupGroup    string
	permsOnlyFlag bool
)

func buildRulesContent(group string) string {
	return fmt.Sprintf(`# 99-voltaire.rules — ASUS ROG Flow Z13 device access
#
# Grants members of the %s group read/write access to:
#   - ASUS HID devices used for keyboard and lightbar RGB control
#   - asus-wmi platform-profile attribute for performance profile control
#   - asus-nb-wmi battery charge_control_end_threshold for battery limit control
#   - Armoury Crate button input device for daemon button watcher
#   - asus-armoury firmware-attributes (boot_sound, panel_overdrive)
#   - cpufreq's global boost switch (perms unit only — udev cannot see it)
#   - hwmon fan curve attributes (asus_custom_fan_curve + asus pwm_enable)
#   - asus-nb-wmi PPT power limit attributes for TDP control
#   - powercap RAPL energy_uj for package-power telemetry (read only)
#
# Generated by: voltaire setup
# To remove: sudo rm /etc/udev/rules.d/99-voltaire.rules && sudo udevadm control --reload-rules
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0b05", ATTRS{idProduct}=="18c6", MODE="0660", GROUP="%s"
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0b05", ATTRS{idProduct}=="1a30", MODE="0660", GROUP="%s"
ACTION=="add", SUBSYSTEM=="platform-profile", RUN+="/usr/bin/chgrp %s /sys%%p/profile", RUN+="/usr/bin/chmod g+w /sys%%p/profile"
ACTION=="add", SUBSYSTEM=="platform-profile", KERNELS=="asus-nb-wmi", RUN+="/usr/bin/chgrp %s /sys/class/power_supply/BAT0/charge_control_end_threshold", RUN+="/usr/bin/chmod g+w /sys/class/power_supply/BAT0/charge_control_end_threshold"
ACTION=="add", SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="Asus WMI hotkeys", MODE="0660", GROUP="%s"
ACTION=="add", SUBSYSTEM=="firmware-attributes", KERNEL=="asus-armoury", RUN+="/usr/bin/chgrp %s /sys/class/firmware-attributes/asus-armoury/attributes/boot_sound/current_value", RUN+="/usr/bin/chmod g+w /sys/class/firmware-attributes/asus-armoury/attributes/boot_sound/current_value"
ACTION=="add", SUBSYSTEM=="firmware-attributes", KERNEL=="asus-armoury", RUN+="/usr/bin/chgrp %s /sys/class/firmware-attributes/asus-armoury/attributes/panel_overdrive/current_value", RUN+="/usr/bin/chmod g+w /sys/class/firmware-attributes/asus-armoury/attributes/panel_overdrive/current_value"
ACTION=="add", SUBSYSTEM=="hwmon", ATTR{name}=="asus_custom_fan_curve", RUN+="/bin/sh -c 'chgrp %s /sys%%p/pwm*; chmod g+w /sys%%p/pwm*'"
ACTION=="add", SUBSYSTEM=="hwmon", ATTR{name}=="asus", RUN+="/bin/sh -c 'for f in /sys%%p/pwm*_enable; do [ -e \"$$f\" ] && chgrp %s \"$$f\" && chmod g+w \"$$f\"; done'"
ACTION=="add", SUBSYSTEM=="platform", KERNEL=="asus-nb-wmi", RUN+="/bin/sh -c 'for f in /sys/devices/platform/asus-nb-wmi/ppt_*; do [ -e \"$$f\" ] && chgrp %s \"$$f\" && chmod g+w \"$$f\"; done'"
ACTION=="add", SUBSYSTEM=="powercap", ATTR{name}=="package-0", RUN+="/bin/sh -c 'for f in /sys%%p/energy_uj; do [ -e \"$$f\" ] && chgrp %s \"$$f\" && chmod g+r \"$$f\"; done'"
`, group, group, group, group, group, group, group, group, group, group, group, group)
}

// buildServiceContent generates the voltaire-perms.service unit file content.
// Handles sysfs files that cannot be set by udev rules:
//   - charge_control_end_threshold: created late in asus_nb_wmi probe()
//   - firmware-attributes current_value: may be created after parent ADD event
//   - ppt_* PPT attributes: created late in the same asus_nb_wmi probe()
//   - ryzen_smu_drv files: kobject under /sys/kernel/, not a udev device
//
// Keep this in sync with contrib/systemd/system/voltaire-perms.service, which is
// what package installs ship; cmd/setup_test.go asserts they do not drift.
// Note the "$$f" doubling is systemd's escape for a literal dollar sign, not Go
// or fmt.Sprintf escaping — a bare "$f" expands to the empty string.
func buildServiceContent(group string) string {
	return fmt.Sprintf(`[Unit]
Description=voltaire sysfs permissions (battery + firmware-attributes + PPT + cpufreq boost + ryzen_smu + powercap)
# charge_control_end_threshold on BAT0 is created by asus_nb_wmi late in probe(),
# after all observable udev child-device events. udev RUN+= cannot catch it.
# firmware-attributes current_value files may be created after the parent ADD event.
# ppt_* on the asus-nb-wmi platform device are created late in the same probe(),
# so the udev rule for them is best-effort only and this service is the reliable path.
# cpufreq's global boost switch is not a udev device at all — the path is a
# plain kobject, so udevadm info answers "Unknown device" and no rule can
# grant it. This unit is the only path.
# ryzen_smu files are under /sys/kernel/, not a udev subsystem.
# powercap energy_uj is 0400 root:root under the Platypus mitigation and is
# granted READ only — write would hand out the package power caps themselves.
After=sysinit.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/sh -c 'for f in /sys/class/power_supply/BAT*/charge_control_end_threshold; do [ -e "$$f" ] && chgrp %s "$$f" && chmod g+w "$$f"; done'
ExecStart=/bin/sh -c 'for f in /sys/class/firmware-attributes/asus-armoury/attributes/boot_sound/current_value /sys/class/firmware-attributes/asus-armoury/attributes/panel_overdrive/current_value; do [ -e "$$f" ] && chgrp %s "$$f" && chmod g+w "$$f"; done'
ExecStart=/bin/sh -c 'for f in /sys/devices/platform/asus-nb-wmi/ppt_*; do [ -e "$$f" ] && chgrp %s "$$f" && chmod g+w "$$f"; done'
ExecStart=/bin/sh -c 'for f in /sys/devices/system/cpu/cpufreq/boost; do [ -e "$$f" ] && chgrp %s "$$f" && chmod g+w "$$f"; done'
ExecStart=/bin/sh -c 'for f in /sys/kernel/ryzen_smu_drv/smu_args /sys/kernel/ryzen_smu_drv/mp1_smu_cmd /sys/kernel/ryzen_smu_drv/rsmu_cmd; do [ -e "$$f" ] && chgrp %s "$$f" && chmod g+w "$$f" || true; done'
ExecStart=/bin/sh -c 'for f in /sys/class/powercap/*/energy_uj; do [ -e "$$f" ] && chgrp %s "$$f" && chmod g+r "$$f"; done'

[Install]
WantedBy=multi-user.target
`, group, group, group, group, group, group)
}

// applySysfsPerms scans live sysfs for files managed by voltaire and either
// applies chgrp/chmod immediately (dryRun=false) or prints what would be done
// (dryRun=true). Errors are silently skipped for missing/inaccessible paths.
// cpuBoostPath is cpufreq's global boost switch, granted group-write so the
// daemon (which runs as the user) can toggle it. The grant is narrow on
// purpose: it is one file, and the only thing it confers is the ability to turn
// boost clocks off — not the power *caps* beside it, which is the same
// distinction that keeps the powercap grant read-only.
const cpuBoostPath = "/sys/devices/system/cpu/cpufreq/boost"

func applySysfsPerms(group string, dryRun bool) {
	chgrpChmod := func(p, mode string) {
		if dryRun {
			fmt.Printf("  chgrp %s %s && chmod %s %s\n", group, p, mode, p)
			return
		}
		_ = exec.Command("chgrp", group, p).Run()
		_ = exec.Command("chmod", mode, p).Run()
	}

	for _, class := range []struct {
		dir  string
		attr string
	}{
		{"/sys/class/platform-profile", "profile"},
		{"/sys/class/power_supply", "charge_control_end_threshold"},
	} {
		entries, err := os.ReadDir(class.dir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			p := class.dir + "/" + e.Name() + "/" + class.attr
			if _, err := os.Stat(p); err != nil {
				continue
			}
			chgrpChmod(p, "g+w")
		}
	}

	// Firmware-attributes (asus-armoury): boot_sound, panel_overdrive.
	for _, attr := range []string{"boot_sound", "panel_overdrive"} {
		p := "/sys/class/firmware-attributes/asus-armoury/attributes/" + attr + "/current_value"
		if _, err := os.Stat(p); err != nil {
			continue
		}
		chgrpChmod(p, "g+w")
	}

	// hwmon fan curve attributes: scan by name for the correct hwmon device.
	hwmonEntries, hwErr := os.ReadDir("/sys/class/hwmon")
	if hwErr == nil {
		for _, e := range hwmonEntries {
			namePath := "/sys/class/hwmon/" + e.Name() + "/name"
			nameBytes, rErr := os.ReadFile(namePath)
			if rErr != nil {
				continue
			}
			name := strings.TrimSpace(string(nameBytes))
			hwBase := "/sys/class/hwmon/" + e.Name()
			switch name {
			case "asus_custom_fan_curve":
				// All pwm* files (curve points + pwm_enable).
				pwmFiles, _ := os.ReadDir(hwBase)
				for _, f := range pwmFiles {
					if strings.HasPrefix(f.Name(), "pwm") {
						chgrpChmod(hwBase+"/"+f.Name(), "g+w")
					}
				}
			case "asus":
				// Only pwm*_enable files (fan mode control).
				pwmFiles, _ := os.ReadDir(hwBase)
				for _, f := range pwmFiles {
					if strings.HasPrefix(f.Name(), "pwm") && strings.HasSuffix(f.Name(), "_enable") {
						chgrpChmod(hwBase+"/"+f.Name(), "g+w")
					}
				}
			}
		}
	}

	// PPT power limit attributes (asus-nb-wmi).
	pptFiles, pptErr := os.ReadDir("/sys/devices/platform/asus-nb-wmi")
	if pptErr == nil {
		for _, f := range pptFiles {
			if strings.HasPrefix(f.Name(), "ppt_") {
				chgrpChmod("/sys/devices/platform/asus-nb-wmi/"+f.Name(), "g+w")
			}
		}
	}

	// cpufreq's global boost switch. Not reachable by udev at all — the path is
	// a plain kobject under /sys/devices/system/cpu, not a device, so
	// `udevadm info` answers "Unknown device" — which makes the perms unit the
	// only path for it and is why there is no matching rule below.
	if _, bErr := os.Stat(cpuBoostPath); bErr == nil {
		chgrpChmod(cpuBoostPath, "g+w")
	}

	// ryzen_smu sysfs files for Curve Optimizer (undervolt).
	if _, smuErr := os.Stat("/sys/kernel/ryzen_smu_drv"); smuErr == nil {
		for _, attr := range []string{"smu_args", "mp1_smu_cmd", "rsmu_cmd"} {
			p := "/sys/kernel/ryzen_smu_drv/" + attr
			if _, err := os.Stat(p); err != nil {
				continue
			}
			chgrpChmod(p, "g+w")
		}
	}

	// powercap RAPL energy counter, for package-power telemetry. Read only:
	// the same directory holds the power-cap controls, and voltaire has no
	// business handing those out to set a graph.
	if capDirs, capErr := os.ReadDir("/sys/class/powercap"); capErr == nil {
		for _, d := range capDirs {
			p := "/sys/class/powercap/" + d.Name() + "/energy_uj"
			if _, err := os.Stat(p); err != nil {
				continue
			}
			chgrpChmod(p, "g+r")
		}
	}

	// Scan for Armoury Crate button input device (Asus WMI hotkeys).
	entries, err := os.ReadDir("/sys/class/input")
	if err == nil {
		for _, e := range entries {
			namePath := "/sys/class/input/" + e.Name() + "/device/name"
			nameBytes, err := os.ReadFile(namePath)
			if err != nil {
				continue
			}
			if strings.TrimSpace(string(nameBytes)) == "Asus WMI hotkeys" {
				chgrpChmod("/dev/input/"+e.Name(), "g+rw")
			}
		}
	}
}

// cleanupOldArtifacts removes what a pre-2.0 "z13ctl setup" installed.
//
// The rules file is deleted only when its header shows it is ours — a file at
// that path we did not generate is someone's local configuration, and deleting
// it would be worse than leaving a stale grant. The old perms unit gets an
// explicit "disable --now" before removal because RemainAfterExit=yes keeps it
// active (holding its enable symlink and stale grants) through anything short
// of that; failures are reported and skipped, since old-name cleanup must
// never stop the new setup from completing.
func cleanupOldArtifacts(dryRun bool) {
	if data, err := os.ReadFile(oldRulesPath); err == nil {
		if strings.Contains(string(data), "Generated by: z13ctl setup") {
			if dryRun {
				fmt.Printf("Would remove old rules file %s\n", oldRulesPath)
			} else if err := os.Remove(oldRulesPath); err != nil {
				fmt.Fprintf(os.Stderr, "note: cannot remove old rules file %s: %v\n", oldRulesPath, err)
			} else {
				fmt.Printf("Removed old rules file %s\n", oldRulesPath)
			}
		} else {
			fmt.Fprintf(os.Stderr, "note: %s was not generated by z13ctl setup; leaving it in place\n", oldRulesPath)
		}
	}

	oldUnitEnabled := exec.Command("systemctl", "is-enabled", "--quiet", oldServiceName).Run() == nil
	_, oldUnitStat := os.Stat(oldServicePath)
	if !oldUnitEnabled && oldUnitStat != nil {
		return
	}
	if dryRun {
		fmt.Printf("Would run: systemctl disable --now %s\n", oldServiceName)
		if oldUnitStat == nil {
			fmt.Printf("Would remove old unit file %s\n", oldServicePath)
		}
		return
	}
	if out, err := exec.Command("systemctl", "disable", "--now", oldServiceName).CombinedOutput(); err != nil {
		fmt.Fprintf(os.Stderr, "note: systemctl disable --now %s failed: %v\n%s", oldServiceName, err, out)
	} else {
		fmt.Printf("Disabled old %s\n", oldServiceName)
	}
	if oldUnitStat == nil {
		if err := os.Remove(oldServicePath); err != nil {
			fmt.Fprintf(os.Stderr, "note: cannot remove old unit file %s: %v\n", oldServicePath, err)
		} else {
			fmt.Printf("Removed old unit file %s\n", oldServicePath)
		}
	}
}

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Install udev rules and boot service for non-root device access",
	Long: `Writes ` + rulesPath + ` granting members of a group read/write
access to the ASUS HID devices used for RGB control, the asus-wmi
platform-profile attribute for performance profile switching, the ACPI
battery charge threshold for battery limit control, the Armoury Crate
button input device for the daemon button watcher, asus-armoury
firmware-attributes (boot sound, panel overdrive), hwmon fan curve
attributes, and asus-nb-wmi PPT power limit attributes for TDP control.
Then reloads and triggers udev so the rules take effect immediately.

Also installs ` + servicePath + `, a small systemd oneshot that
runs 'chgrp' and 'chmod g+w' at boot on the battery charge threshold, the
asus-armoury firmware-attributes, the PPT power limit attributes, and the
ryzen_smu files. This is required because those attributes are created late in
the asus_nb_wmi kernel driver's probe() sequence (after all udev events have
already fired), or live outside any udev subsystem.

Use --perms-only to skip writing the rules file and only reapply sysfs
permissions (useful after a group change or kernel module reload).

Use --dry-run to preview exactly what would be written and which sysfs files
would be chmod'd, without making any changes (no root required).

This command must be run with sudo (unless --dry-run is used).`,
	RunE: func(_ *cobra.Command, _ []string) error {
		if dryRunFlag {
			if permsOnlyFlag {
				fmt.Println("=== DRY RUN: would reapply sysfs permissions ===")
			} else {
				fmt.Println("=== DRY RUN (no changes will be made) ===")
				fmt.Printf("\nWould write %s:\n\n", rulesPath)
				fmt.Print(buildRulesContent(setupGroup))
				fmt.Println("Would run: udevadm control --reload-rules")
				fmt.Println("Would run: udevadm trigger --subsystem-match=hidraw")
				fmt.Printf("\nWould write %s:\n\n", servicePath)
				fmt.Print(buildServiceContent(setupGroup))
				fmt.Println("Would run: systemctl daemon-reload")
				fmt.Println("Would run: systemctl enable --now voltaire-perms.service")
				cleanupOldArtifacts(true)
			}
			fmt.Println("\nWould apply sysfs permissions (files present on this system):")
			applySysfsPerms(setupGroup, true)
			return nil
		}

		if os.Getuid() != 0 {
			return fmt.Errorf("this command requires root — run with sudo:\n  sudo voltaire setup\n\nTo preview changes without root: voltaire --dry-run setup")
		}

		// --perms-only: just reapply sysfs permissions, skip rules and service.
		if permsOnlyFlag {
			applySysfsPerms(setupGroup, false)
			return nil
		}

		content := buildRulesContent(setupGroup)
		if err := os.WriteFile(rulesPath, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", rulesPath, err)
		}
		fmt.Printf("Wrote %s (group: %s)\n", rulesPath, setupGroup)

		// Remove the pre-rename artifacts after the new rules exist and before
		// udev reloads, so there is no window with neither rules file in place
		// and the reload below picks up the removal too.
		cleanupOldArtifacts(false)

		if out, err := exec.Command("udevadm", "control", "--reload-rules").CombinedOutput(); err != nil {
			return fmt.Errorf("udevadm control --reload-rules: %w\n%s", err, out)
		}
		fmt.Println("Reloaded udev rules.")

		if out, err := exec.Command("udevadm", "trigger", "--subsystem-match=hidraw").CombinedOutput(); err != nil {
			return fmt.Errorf("udevadm trigger: %w\n%s", err, out)
		}
		fmt.Println("Triggered udev rules.")

		// systemd 259+ does not execute RUN{program} for synthetic udevadm trigger
		// events, so apply sysfs permissions directly. The udev rules cover
		// subsequent boots via real kernel ADD events.
		applySysfsPerms(setupGroup, false)
		fmt.Println("Applied sysfs permissions.")

		// Install the battery permissions service. charge_control_end_threshold is
		// created late in asus_nb_wmi probe(), after all udev events have fired, so
		// udev RUN+= cannot set its permissions reliably at boot.
		svcContent := buildServiceContent(setupGroup)
		if err := os.WriteFile(servicePath, []byte(svcContent), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", servicePath, err)
		}
		fmt.Printf("Wrote %s\n", servicePath)
		if out, err := exec.Command("systemctl", "daemon-reload").CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "note: systemctl daemon-reload failed: %v\n%s", err, out)
			fmt.Fprintf(os.Stderr, "Enable the service manually: sudo systemctl enable --now voltaire-perms.service\n")
		} else if out, err := exec.Command("systemctl", "enable", "--now", "voltaire-perms.service").CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "note: systemctl enable failed: %v\n%s", err, out)
			fmt.Fprintf(os.Stderr, "Enable the service manually: sudo systemctl enable --now voltaire-perms.service\n")
		} else {
			fmt.Println("Enabled voltaire-perms.service.")
		}

		fmt.Printf("\nDone. Members of the '%s' group can now run voltaire without sudo.\n", setupGroup)
		fmt.Println("This covers RGB control, performance profiles, battery charge limiting,")
		fmt.Println("the Armoury Crate button, boot sound, panel overdrive, fan curves,")
		fmt.Println("TDP, CPU boost, and undervolt (if ryzen_smu is installed).")
		fmt.Printf("If your user is not in '%s', add it with:\n", setupGroup)
		fmt.Printf("  sudo usermod -aG %s $USER\n", setupGroup)
		fmt.Println("Then log out and back in for the group change to take effect.")
		return nil
	},
}

func init() {
	setupCmd.Flags().StringVar(&setupGroup, "group", "users", "Group to grant access to the ASUS HID devices")
	setupCmd.Flags().BoolVar(&permsOnlyFlag, "perms-only", false, "Reapply sysfs permissions without writing udev rules or service")
	rootCmd.AddCommand(setupCmd)
}
