package cmd

// setup.go — "setup" subcommand: install udev rules for non-root device access.

import (
	"fmt"
	"os"
	"os/exec"

	"github.com/spf13/cobra"
)

const rulesPath = "/etc/udev/rules.d/99-z13ctl.rules"

var setupGroup string

func buildRulesContent(group string) string {
	return fmt.Sprintf(`# 99-z13ctl.rules — ASUS ROG Flow Z13 device access
#
# Grants members of the %s group read/write access to:
#   - ASUS HID devices used for keyboard and lightbar RGB control
#   - asus-wmi platform-profile attribute for performance profile control
#   - ACPI battery charge_control_end_threshold for battery limit control
#
# Generated by: z13ctl setup
# To remove: sudo rm /etc/udev/rules.d/99-z13ctl.rules && sudo udevadm control --reload-rules
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0b05", ATTRS{idProduct}=="18c6", MODE="0660", GROUP="%s"
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0b05", ATTRS{idProduct}=="1a30", MODE="0660", GROUP="%s"
ACTION=="add", SUBSYSTEM=="platform-profile", ATTR{name}=="asus-wmi", RUN+="/bin/chgrp %s /sys%%p/profile", RUN+="/bin/chmod g+w /sys%%p/profile"
ACTION=="add", SUBSYSTEM=="power_supply", KERNEL=="BAT*", RUN+="/bin/chgrp %s /sys%%p/charge_control_end_threshold", RUN+="/bin/chmod g+w /sys%%p/charge_control_end_threshold"
`, group, group, group, group, group)
}

// applySysfsPerms scans live sysfs for files managed by z13ctl and either
// applies chgrp/chmod immediately (dryRun=false) or prints what would be done
// (dryRun=true). Errors are silently skipped for missing/inaccessible paths.
func applySysfsPerms(group string, dryRun bool) {
	chgrpChmod := func(p string) {
		if dryRun {
			fmt.Printf("  chgrp %s %s && chmod g+w %s\n", group, p, p)
			return
		}
		_ = exec.Command("chgrp", group, p).Run()
		_ = exec.Command("chmod", "g+w", p).Run()
	}

	for _, class := range []struct {
		dir  string
		attr string
	}{
		{"/sys/class/platform-profile", "profile"},
		{"/sys/class/power_supply", "charge_control_end_threshold"},
	} {
		entries, err := os.ReadDir(class.dir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			p := class.dir + "/" + e.Name() + "/" + class.attr
			if _, err := os.Stat(p); err != nil {
				continue
			}
			chgrpChmod(p)
		}
	}
}

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Install udev rules to allow non-root access to ASUS devices",
	Long: `Writes ` + rulesPath + ` granting members of a group read/write
access to the ASUS HID devices used for RGB control, the asus-wmi
platform-profile attribute for performance profile switching, and the ACPI
battery charge threshold for battery limit control. Then reloads and triggers
udev so the rules take effect immediately.

Use --dry-run to preview exactly what would be written and which sysfs files
would be chmod'd, without making any changes (no root required).

This command must be run with sudo (unless --dry-run is used).`,
	RunE: func(_ *cobra.Command, _ []string) error {
		if dryRunFlag {
			fmt.Println("=== DRY RUN (no changes will be made) ===")
			fmt.Printf("\nWould write %s:\n\n", rulesPath)
			fmt.Print(buildRulesContent(setupGroup))
			fmt.Println("Would run: udevadm control --reload-rules")
			fmt.Println("Would run: udevadm trigger --subsystem-match=hidraw")
			fmt.Println("\nWould apply sysfs permissions (files present on this system):")
			applySysfsPerms(setupGroup, true)
			return nil
		}

		if os.Getuid() != 0 {
			return fmt.Errorf("this command requires root — run with sudo:\n  sudo z13ctl setup\n\nTo preview changes without root: z13ctl --dry-run setup")
		}

		content := buildRulesContent(setupGroup)
		if err := os.WriteFile(rulesPath, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", rulesPath, err)
		}
		fmt.Printf("Wrote %s (group: %s)\n", rulesPath, setupGroup)

		if out, err := exec.Command("udevadm", "control", "--reload-rules").CombinedOutput(); err != nil {
			return fmt.Errorf("udevadm control --reload-rules: %w\n%s", err, out)
		}
		fmt.Println("Reloaded udev rules.")

		if out, err := exec.Command("udevadm", "trigger", "--subsystem-match=hidraw").CombinedOutput(); err != nil {
			return fmt.Errorf("udevadm trigger: %w\n%s", err, out)
		}
		fmt.Println("Triggered udev rules.")

		// systemd 259+ does not execute RUN{program} for synthetic udevadm trigger
		// events, so apply sysfs permissions directly. The udev rules cover
		// subsequent boots via real kernel ADD events.
		applySysfsPerms(setupGroup, false)
		fmt.Println("Applied sysfs permissions.")

		fmt.Printf("\nDone. Members of the '%s' group can now run z13ctl without sudo.\n", setupGroup)
		fmt.Println("This covers RGB control, performance profiles, and battery charge limiting.")
		fmt.Printf("If your user is not in '%s', add it with:\n", setupGroup)
		fmt.Printf("  sudo usermod -aG %s $USER\n", setupGroup)
		fmt.Println("Then log out and back in for the group change to take effect.")
		return nil
	},
}

func init() {
	setupCmd.Flags().StringVar(&setupGroup, "group", "users", "Group to grant access to the ASUS HID devices")
	rootCmd.AddCommand(setupCmd)
}
