// setup.go — "setup" subcommand: install udev rules for non-root device access.
package cmd

import (
	"fmt"
	"os"
	"os/exec"

	"github.com/spf13/cobra"
)

const rulesPath = "/etc/udev/rules.d/99-z13ctl.rules"

var setupGroup string

func buildRulesContent(group string) string {
	return fmt.Sprintf(`# 99-z13ctl.rules — ASUS ROG Flow Z13 RGB control
#
# Grants members of the %s group read/write access to the ASUS HID
# devices used for keyboard and lightbar RGB control.
#
# Generated by: z13ctl setup
# To remove: sudo rm /etc/udev/rules.d/99-z13ctl.rules && sudo udevadm control --reload-rules
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0b05", ATTRS{idProduct}=="18c6", MODE="0660", GROUP="%s"
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0b05", ATTRS{idProduct}=="1a30", MODE="0660", GROUP="%s"
`, group, group, group)
}

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Install udev rules to allow non-root access to ASUS RGB devices",
	Long: `Writes ` + rulesPath + ` granting members of a group read/write
access to the ASUS HID devices used for RGB control, then reloads and triggers
udev so the rules take effect immediately.

This command must be run with sudo.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if os.Getuid() != 0 {
			return fmt.Errorf("this command requires root — run with sudo:\n  sudo z13ctl setup")
		}

		content := buildRulesContent(setupGroup)
		if err := os.WriteFile(rulesPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("write %s: %w", rulesPath, err)
		}
		fmt.Printf("Wrote %s (group: %s)\n", rulesPath, setupGroup)

		if out, err := exec.Command("udevadm", "control", "--reload-rules").CombinedOutput(); err != nil {
			return fmt.Errorf("udevadm control --reload-rules: %w\n%s", err, out)
		}
		fmt.Println("Reloaded udev rules.")

		if out, err := exec.Command("udevadm", "trigger", "--subsystem-match=hidraw").CombinedOutput(); err != nil {
			return fmt.Errorf("udevadm trigger: %w\n%s", err, out)
		}
		fmt.Println("Triggered udev rules.")

		fmt.Printf("\nDone. Members of the '%s' group can now run z13ctl without sudo.\n", setupGroup)
		fmt.Printf("If your user is not in '%s', add it with:\n", setupGroup)
		fmt.Printf("  sudo usermod -aG %s $USER\n", setupGroup)
		fmt.Println("Then log out and back in for the group change to take effect.")
		return nil
	},
}

func init() {
	setupCmd.Flags().StringVar(&setupGroup, "group", "users", "Group to grant access to the ASUS HID devices")
	rootCmd.AddCommand(setupCmd)
}
