// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';

// https://astro.build/config
export default defineConfig({
	site: 'https://dahui.github.io',
	base: '/voltaire',
	integrations: [
		starlight({
			title: 'Voltaire',
			description:
				'RGB lighting, fan curves, TDP, and system control for the 2025 ASUS ROG Flow Z13 on Linux.',
			social: [
				{
					icon: 'github',
					label: 'GitHub',
					href: 'https://github.com/dahui/voltaire',
				},
			],
			editLink: {
				baseUrl: 'https://github.com/dahui/voltaire/edit/main/website/',
			},
			plugins: [
				starlightLinksValidator({
					// reference/api-go.md is generated by gomarkdoc (make docs-api);
					// its #Symbol fragment links target raw <a name> anchors the
					// validator cannot see. Every hand-written page stays validated.
					exclude: ({ file }) => file.endsWith('reference/api-go.md'),
				}),
			],
			sidebar: [
				{
					label: 'Start Here',
					items: [
						{ label: 'Installation', slug: 'installation' },
						{ label: 'Quick Start', slug: 'quick-start' },
						{ label: 'Migrating from z13ctl', slug: 'migrating-from-z13ctl' },
					],
				},
				{
					label: 'The GUI',
					items: [
						{ label: 'Overview', slug: 'gui' },
						{ label: 'Quick Start', slug: 'gui/quick-start' },
						{ label: 'Configuration', slug: 'gui/configuration' },
						{ label: 'Theming', slug: 'gui/theming' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'Commands', slug: 'reference/commands' },
						{ label: 'Daemon & Socket Protocol', slug: 'reference/daemon' },
						{ label: 'Go API Module', slug: 'reference/api' },
						{ label: 'Go API Reference', slug: 'reference/api-go' },
						{ label: 'HID Protocol', slug: 'reference/protocol' },
					],
				},
				{
					label: 'Project',
					items: [
						{ label: 'Contributing', slug: 'contributing' },
						{ label: 'Z13 Hardware Smoke Test', slug: 'dev/smoke-z13' },
					],
				},
			],
		}),
	],
});
